### ISSUE TITLE
テンプレートキャッシュのデフォルト位置を変更したい

### ISSUE THREAD

**Issue by kazuyuki-saka** [genies-inc/Fegg#18]
feggディレクトリ配下、あるいはtemplateディレクトリ配下にしたい。

**Comment by sus-happy** [comment]
テンプレートエンジンを切り離しやすくするためでしょうか？
そうであればdataディレクトリも外に出しても良さそうな気がしました。

どちらかと言うと個人的にはtemplateディレクトリ配下だと嬉しいです。
（feggディレクトリ配下は核となるファイルが入ってるイメージがあるので）

**Comment by kazuyuki-saka** [comment]
そうですね、\template\_cache　（一番上に持ってきたいため _ 付ける）とかですかね。
あくまでデフォルトなので、$settingsファイルの初期値の話になります。
なので、いまでもやろうと思えばできます。

dataは、これまでの流れで存在していて、そこにcacheが置かれてるって感じなので、取決めは特にないです。外に出してもらってよいかと思います。

**Comment by sus-happy** [comment]
/template/_cache 良いですね、dataはcode配下で、templateだけ外に出すのがしっくり来そうです。
（dataにはapplicationファイルからのログとかマスタとかを入れそうなので）

**Comment by kazuyuki-saka** [comment]
c78c2b97fbda3b7c66d6ab419e92b5aef9e0c001 にて対応しました。
